### ISSUE TITLE
Chokehold (Exile) does not properly Silence the target.

### ISSUE THREAD

**Issue by InquisitorGrand** [hiddenswitch/Spellsource#1427]
Spellsource Reproducible Issue Template

Reproduction steps:

 1. Perform action 1
 2. Perform action 2
 3. Observe X. The user expects Y.
 
Platform: [ ] Windows, [ ] Mac

Design or Graphics Glitches: Please attach a screenshot.

**Comment by doctorpangloss** [comment]
needs more info
