### ISSUE TITLE
Paven coming out of its dormant state doesn't trigger Farseer Kethaan (or its dormant version)

### ISSUE THREAD

**Issue by BlobSlime** [hiddenswitch/Spellsource#1572]
1. Play Paven, Elemental of Surprise
2. Have the Paven die
3. Play Farseer Kethaan
4. Play a discover card to revive Paven
5. Paven resummoning does not trigger Kethaan. However, it should gain the +2/+2 buff(?).

Honestly, I'm not sure how dormant and coming out of dormant works, so maybe this is the intended interaction? I have no idea...

**Comment by doombubbles** [comment]
For the moment at least, this seems like the intended interaction.

Minions go dormant and un-dormant by transforming back and forth between permanent and non-permanent versions, and transformations don't trigger summon effects.
