### ISSUE TITLE
Change Invoke and implement new summoner (see details)

### ISSUE THREAD

**Issue by TheFlawlessWalrus** [hiddenswitch/Spellsource#1576]
[Summoner 2.zip](https://github.com/hiddenswitch/Spellsource/files/4327490/Summoner.2.zip)
Intended as a replacement to the entire Summoner Core, as well as changes to the classes hero power, name and colour. Originally intended to come after an Invoke update but that didn't happen.

Important to note that the rare card Kindred Ritual and the epic cards Deep Envoy and Rune of Banishing are stubs, as I've no clue how to program them myself.

**Comment by doctorpangloss** [comment]
Invoke (X): If you have X lun leftover after playing this card, receive an ethereal card that does... (Ethereal cards go away next turn). It costs X

**Comment by doombubbles** [comment]
It's finally done!
