### ISSUE TITLE
Mysterious Questgiver doesn't discover any 1-cost Timeweaver cards.

### ISSUE THREAD

**Issue by BlobSlime** [hiddenswitch/Spellsource#1579]
1. Play Mysterious Questgives
2. You won't discover anything. However, you should be able to discover the cards.

**Comment by doombubbles** [comment]
I can't recreate this specific problem now. It appears you just always discover Arcane Accelerator or Reload Rodger. An issue that I can see though is that it only does one discovery, while it's opener is "Discover _three_ 1-Cost Timeweaver minions." I will fix that in relation to this issue, but this card seems in need of a revisit, or at least some new 1-Cost Timeweaver minions being created.

**Comment by BlobSlime** [comment]
Ah okay, that makes sense. Probably should've checked that out before hand. However, Timeweaver will be getting deleted soon anyways, so this card will be too.
