### ISSUE TITLE
Scavenged Steel gives the choice of choosing between 2 weapons, once. However, it should discover (choose between 3), twice.

### ISSUE THREAD

**Issue by BlobSlime** [hiddenswitch/Spellsource#1581]
1. Play Scavenged Steel
2. The card will pull up a UI of choosing between 2 weapons. However, it should discover between 3 weapons, and then the UI of another 3 weapons.

**Comment by doombubbles** [comment]
I wasn't able to reproduce this bug either in the live game or a testing environment. I'll close this issue for now, but if it comes up again please submit a new issue and include as much info about the circumstances as possible.

**Comment by BlobSlime** [comment]
At the time of this ticket, it was a bug, but i believe Dipsy (DeepKhaos) has since fixed it. Sorry, i should’ve closed it myself.
