### ISSUE TITLE
The Oathbreaker in Overlord reduces the cost of all pacts he draws, not just the first one you play.

### ISSUE THREAD

**Issue by Bromora** [hiddenswitch/Spellsource#1613]
1. Old pacts before my recent additions need to be given the PACT attribute.
2. Coven’s Debt also can have its condition based on playing a card with the PACT attribute instead of being hard coded for specific pacts.

**Comment by doombubbles** [comment]
Seems like all the other Pacts have got the PACT attribute already 👍
