### ISSUE TITLE
I got an instant defeat screen while fighting Bromara in match making when the game started

### ISSUE THREAD

**Issue by Pircival** [hiddenswitch/Spellsource#1643]
Spellsource Reproducible Issue Template

Reproduction steps:

 1. Perform action 1
 2. Perform action 2
 3. Observe X. The user expects Y.
 
Platform: [ ] Windows, [ ] Mac

Design or Graphics Glitches: Please attach a screenshot.

**Comment by doombubbles** [comment]
Not really enough info to go off of, as I don't think Bromara is bugged. Basically need to know the classes and decks being played. I'll probably close this by the end of the week w/o additional deets.
