### ISSUE TITLE
Finale Architect does nothing if it dies

### ISSUE THREAD

**Issue by TheFlawlessWalrus** [hiddenswitch/Spellsource#1646]
When you cast a spell while you have a Finale Architect on the board, the spell triggers at the start of the next turn. If Finale Architect dies, however, it does not. This is not the intention, and Finale Architect's enchantment should probably be applied to the champion when it triggers, rather than itself.

**Comment by doombubbles** [comment]
This is a bit strange. The enchantment does get applied to the player entity, and not the minion. I've tested it with a few random spells like Chain Dance and Star Performance, and it still casts those after dying. Maybe it's an issue with just certain specific spells or situations? Need more info
