### ISSUE TITLE
Allow cards to be removed from the deck without going to the graveyard; or add functions that work like "PutDeckTopSpell" and "PutOnBottomOfDeckSpell" but move the card directly instead of creating copies

### ISSUE THREAD

**Issue by TheBuggg** [hiddenswitch/Spellsource#1655]
"PutDeckTopSpell" and "PutOnBottomOfDeckSpell," if targeting a specific existing card, create copies rather than moving, and as such existing cards that use them targetting specific cards use the "RemoveCardSpell" to remove the original copies (e.g. Plan Ahead).
However, this does cause those cards to be put in the graveyard, which does not logically follow from the card. Normally this would not be problematic but as graveyard synergies are becoming increasingly prevalent the unusual behavior may become noticeable.

**Comment by doombubbles** [comment]
Although the cards are added to the `GRAVEYARD` zone, they aren't given an attribute like `PLAYED_FROM_HAND_OR_DECK`, `DISCARDED` or `ROASTED`, so any Graveyard synergies *should* already be equipped to handle their presence in the zone. If any of them aren't, they can likely be fixed simply with just an `AttributeFilter`. If you encounter any such sus behavior, definitely ticket it.
