### ISSUE TITLE
Spirit Sabre in VL is... glitchy

### ISSUE THREAD

**Issue by Bromora** [hiddenswitch/Spellsource#1657]
It copies an aftermath that has been triggered, but if it has been triggered off of a minion with “hate spike” and then said minion gets transformed: spirit sabre will show the transformed minion instead of the original’s aftermath (it also will not trigger the aftermath from selecting the transformation). Secondly, if you played a sabre before, then the second sabre can get the original as an option, even though the aftermath is not the sabre’s itself (I’m guessing the result is also the same with not actually having an aftermath, didn’t test at the time) an example of the latter can be seen below.

![CCBA8AD7-6B41-4921-AB1D-73190CD2D3D5](https://user-images.githubusercontent.com/18221278/78016979-7b7cc900-7343-11ea-92bb-3106e35af1a5.png)

**Comment by doombubbles** [comment]
At the moment, (aka without doing an entire revamp of the way Aftermaths are handled internally and externally), what I can do is fix the transform bug at least. When you play Spirit Saber, it will look at all the different aftermaths that have triggered for you this game, choose 3 of them, and then show you the exact card that had the aftermath when it was triggered. 
So, you *will* still be able to see your first Spirit Saber if you play a second one, and it will represent the aftermath you chose for it the first time. This means there will be some memory involved, and come to think of it randomness, if you had the same actor trigger multiple different aftermaths throughout the game.
If that revamp does happen in the future, we can revisit this card and maybe make it work a little bit nicer.
