### ISSUE TITLE
Stays on loading screen forever

### ISSUE THREAD

**Issue by Nixolium** [hiddenswitch/Spellsource#1659]
Spellsource Reproducible Issue Template

Reproduction steps:

 1. Mistype cards in the in-game card creator. I'm not entirely sure, which error resulted in this. I know I was messing with changing hero powers on the Deathrattle of weapons.
 2. The game freezes. Cards cannot be played, and the turn cannot be ended.
 3. Close the game.
 4. Upon attempting to reload the game, it forever states "LOADING..."
 
Platform: [ X ] Windows, [ ] Mac

**Comment by doctorpangloss** [comment]
Fixed by restarting the server :/
