### ISSUE TITLE
Update decks for all classes

### ISSUE THREAD

**Issue by doctorpangloss** [hiddenswitch/Spellsource#1681]

**Comment by doombubbles** [comment]
Comment decks here!

**Comment by skurleton** [comment]
### Ramp Storyteller
# Class: OLIVE
# Format: Spellsource
#
# 1x (1) Alagard, Mythologist
# 2x (1) Flying Fiction
# 2x (2) Engaging Story
# 2x (3) Bored to Death
# 2x (3) Captain of the Guard
# 2x (3) Cinderslinger
# 2x (4) Cursebrewing Witch
# 2x (4) Defender of Tomorrow
# 1x (4) Miserable Conclusion
# 2x (4) Primal Mother
# 1x (5) Lord of the Sea
# 2x (5) Tome of Nourishing
# 1x (6) Inora, Spellbound
# 2x (7) Chained Chimera
# 2x (7) Manly Mountaineer
# 1x (9) Queen Cinderella
# 2x (10) Mollusk Meister
# 1x (10) Sourceborn Aelin
#

**Comment by doombubbles** [comment]
### First Flight
# Class: AZURE
# Format: Spellsource
#
# 2x (1) Enhancing Shaman
# 2x (1) Skywalker
# 2x (1) Solis Caster
# 2x (2) Blow Away
# 2x (2) Channeled Spirit
# 2x (2) Fluttering Songbird
# 2x (2) Lightning Strike
# 2x (2) Nimbus Strider
# 1x (3) Explore the Endless Skies
# 2x (3) Spirited Sprite
# 2x (3) Wind's Grace
# 2x (4) Evasive Cirrus
# 2x (4) Fae Harbinger
# 2x (6) Faerie Squadron
# 2x (6) Typhoon
# 1x (7) Stormbringer Kurt
#

**Comment by InquisitorGrand** [comment]
### Rebel Rebel
# Class: CAMO
# Format: Spellsource
#
# 2x (1) Double Strike
# 2x (2) Burrows Sniper
# 2x (2) Low Sweep
# 2x (2) Power of the People
# 2x (2) Smokescreen
# 2x (3) Chokehold
# 2x (3) Pilfered Dagger
# 2x (3) Skirmish
# 1x (4) Bogovanis
# 2x (7) Last Man Standing
# 1x (8) Primalist Kirra
# 2x (8) Soup Savant
# 1x (9) Smogg
# 1x (10) Dream of Freedom
# 1x (10) End
# 2x (10) Fel Manticore
# 2x (10) Mollusk Meister
# 1x (10) Sourceborn Aelin

**Comment by BlobSlime** [comment]
### Hidden Queen
# Class: BLUEGREY
# Format: Spellsource
#
# 2x (0) Cloak and Dagger
# 2x (0) Dimensiongate
# 1x (1) Enenra
# 2x (1) Gather in the Shadows
# 2x (1) Shadow Ninja
# 2x (1) Shinobi Infiltrator
# 2x (1) Thin Smoke
# 2x (2) Swiftfoot Shinobi
# 2x (2) Terrified Tanuki
# 2x (3) Shady Namahage
# 2x (3) Smoke Flash
# 2x (3) Smokeweaver
# 2x (3) Stormcloud Assailant
# 2x (3) Warmongering
# 1x (5) Nurse Wounds
# 2x (6) 8th Heaven Formation
#
