### ISSUE TITLE
Relics of Deities doesn't work

### ISSUE THREAD

**Issue by Muhframos** [hiddenswitch/Spellsource#1687]
Spellsource Reproducible Issue Template

Reproduction steps:

 1. Play Relics of Deities
 2. Don't draw anything
 3. It should draw something and do the effect, but at least when i played it, it simply didnt.
 
Platform: [X] Windows, [ ] Mac

Design or Graphics Glitches: Please attach a screenshot.

**Comment by doombubbles** [comment]
The card works fine for me in my testing. Did you definitely have spells in your deck at the time?

**Comment by Muhframos** [comment]
Hmm, i wonder if thats what happened
maybe i just confused the cards

**Comment by doombubbles** [comment]
Ok, I'll close this issue for now, but we can keep an eye on it
