### ISSUE TITLE
Edit pencil icon missing from one of the two orientations of the battlefield's card editor button

### ISSUE THREAD

**Issue by doctorpangloss** [hiddenswitch/Spellsource#1748]

**Comment by lee08** [comment]
This is rather a very simple fix, I am just hesistant to commit because the change is in Assets/Scenes/Game.unity which also has other gunk changed just by opening a scene.
One of the Pencil objects is just missing the sprite.

**Comment by doctorpangloss** [comment]
@lee08 just commit it i will resolve the merge issues
